cursotelmex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


admin.autodiscover()

urlpatterns = [
    url( r'^login/$',auth_views.LoginView.as_view(template_name="movies/index.html"), name="login"),
    url( r'^login1/$',auth_views.LoginView.as_view(template_name="movies/index1.html"), name="login"),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('movies.urls',namespace='movies')),
	url(r'api/v1/',include('movies.urls',namespace='apis') ),
	url('accounts/', include('allauth.urls')),
    path('', include('pwa.urls')),
]

urlpatterns += [
	url(r'^api/v1/auth/', include('rest_framework.urls', namespace='rest_framework'))
]

movies/urls.py
from django.conf.urls import url

from . import views
from django.contrib import admin
from movies.views import InteresadosList,MascotasList

app_name= 'movies'

urlpatterns = [
    url(
        regex=r'^hello/$',
        view=views.hello_world,
        name='hello_world'
    ),

    url(
        regex=r'^interesados/$',
        view=views.list_interesados,
        name='list'
    ),

    url(
        regex=r'^crear-lista/$',
        view=views.create_interesados,
        name='new_interesados'
    ),

    url(
        regex=r'^listas/$',
        view=views.list_interesados,
        name='interesados'
    ),

    url(
        regex=r'^listas/(?P<id>\d+)/$',
        view=views.detail_interesados,
        name='detail_interesados'
    ),

    url(
        regex=r'^editar-lista/(?P<id>\d+)/$',
        view=views.update_interesados,
        name='edit_interesados'
    ),

    url(
        regex=r'^borrar-lista/(?P<id>\d+)/$',
        view=views.delete_interesados,
        name='delete_interesados'
    ),

    url(
        regex=r'^mascotas/$',
        view=views.list_mascotas,
        name='listmascotas'
    ),

    url(
        regex=r'^crear-mascota/$',
        view=views.create_mascotas,
        name='new_mascotas'
    ),

    url(
        regex=r'^listas_mascotas/$',
        view=views.list_mascotas,
        name='mascotas'
    ),

    url(
        regex=r'^listas_mascotas/(?P<id>\d+)/$',
        view=views.detail_mascotas,
        name='detail_mascotas'
    ),

    url(
        regex=r'^editar-mascotas/(?P<id>\d+)/$',
        view=views.update_mascotas,
        name='edit_mascotas'
    ),

    url(
        regex=r'^borrar-mascota/(?P<id>\d+)/$',
        view=views.delete_mascotas,
        name='delete_mascotas'
    ),

    url(
        regex=r'^estados/$',
        view=views.list_estados,
        name='listestados'
    ),

    url(
        regex=r'^crear-estados/$',
        view=views.create_estados,
        name='new_estados'
    ),

    url(
        regex=r'^listas_estados/$',
        view=views.list_estados,
        name='estados'
    ),

    url(
        regex=r'^listas_estados/(?P<id>\d+)/$',
        view=views.detail_estados,
        name='detail_estados'
    ),

    url(
        regex=r'^editar-estados/(?P<id>\d+)/$',
        view=views.update_estados,
        name='edit_estados'
    ),

    url(
        regex=r'^borrar-estados/(?P<id>\d+)/$',
        view=views.delete_estados,
        name='delete_estados'
    ),
	url(r'^interesadoslist/', InteresadosList.as_view(), name='interesadoslist'),
	url(r'^mascotaslist/', MascotasList.as_view(), name='mascotaslist')
]

movies/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator

User = get_user_model()


class Region(models.Model):
    """Modelo de Estudio de cine."""

    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name		

class Ciudad(models.Model):
    """Modelo de Estudio de cine."""

    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name		

class Vivienda(models.Model):
    """Modelo de Estudio de cine."""

    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

class Razaprodominante(models.Model):
    """Modelo de Estudio de cine."""

    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name		

class Estados(models.Model):
    """Modelo de Estudio de cine."""

    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name
		
	
		
	
class Interesados(models.Model):
 rut = models.CharField('Rut', max_length=12)
 nombrecompleto = models.CharField('Nombre Completo', max_length=100)
 correo = models.EmailField()
 telefono = models.IntegerField()
 region = models.ManyToManyField('Region')
 ciudad = models.ManyToManyField('Ciudad')
 vivienda = models.ManyToManyField('Vivienda')
 fecha_nacimiento = models.DateField('Fecha de nacimiento')
 password = models.CharField(max_length=50)
 
 def __str__(self):
        return self.nombrecompleto
		
		

class Mascotas(models.Model):
 nombre = models.CharField('Nombre mascota', max_length=20)
 razap = models.ManyToManyField('Razaprodominante')
 descripcion = models.CharField(max_length=30)
 estados= models.ManyToManyField('Estados')
 image = models.ImageField(upload_to='albums/images/')
 
 def __str__(self):
        return self.nombre
		


	

movies/forms.py
from django import forms

from .models import  Mascotas, Interesados,Estados


class MascotaListForm(forms.ModelForm):

    class Meta:
        model = Mascotas
        fields = '__all__'

class InteresadosForm(forms.ModelForm):

    class Meta:
        model = Interesados
        fields = '__all__'

class EstadosForm(forms.ModelForm):

    class Meta:
        model = Estados
        fields = '__all__'
		
class MascotasForm(forms.ModelForm):

    class Meta:
        model = Mascotas
        fields = '__all__'

movies/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import generics
from .serializers import interesasosSerializer, MascotaSerializer
import json

from .models import (
	Interesados,
	Mascotas,
	Estados
)

from .forms import MascotaListForm,InteresadosForm, MascotasForm, EstadosForm


def hello_world(request):
    """Ejemplo de view que sólo muestra un "Hola mundo" en el navegador."""
    return HttpResponse("Hello world!")

	
"""Administración de interesados********************************************************************************************"""

def create_interesados(request):
    """View para crear una nueva lista películas por ver."""
    if request.method == "POST":
        form = InteresadosForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:interesados")
        else:
            errors = form.errors
            context = {
                'form': form,
                'errors': errors
            }
            return render(request, 'movies/new_interesados.html', context)
    else:
        form = InteresadosForm()
        context = {
            'form': form
        }
        return render(request, 'movies/new_interesados.html', context)


def list_interesados(request):
    """View que enlista MovieList que hay en la base de datos."""
    lists = Interesados.objects.all().order_by('nombrecompleto')
    context =  {
        'lists': lists
    }

    return render(request, 'movies/list_interesados.html', context)

def detail_interesados(request, id):
    """View que muestra el detalle de una lista."""
    object = get_object_or_404(Interesados, pk=id)
    context = {
        'list': object
    }

    return render(request, 'movies/detail_interesados.html', context)

def update_interesados(request, id):
    """View para editar una lista."""
    object = get_object_or_404(Interesados, pk=id)
    if request.method == "POST":
        form = InteresadosForm(request.POST, instance=object)
        if form.is_valid():
            form.save()
            return redirect("movies:interesados")
        else:
            errors = form.errors
            context = {
                'form': form,
                'errors': errors
            }
            return render(request, 'movies/new_interesados.html', context)
    else:
        form = InteresadosForm(instance=object)
        context = {
            'form': form,
            'list': object
        }
        return render(request, 'movies/new_interesados.html', context)


def delete_interesados(request, id):
    """
    View para borrar una lista. Si es un método GET, le pedimos confirmación
    al usuario. Si es un método POST, significa que el usuario ha confirmado
    y podemos borrar la lista.
    """
    object = get_object_or_404(Interesados, pk=id)

    if request.method == "POST":
        object.delete()
        return redirect("movies:interesados")
    else:
        return render(request, "movies/delete_interesados.html", {'list': object})

		
		
"""Administración de Mascotas********************************************************************************************"""

def create_mascotas(request):
    """View para crear una nueva lista películas por ver."""
    if request.method == "POST":
        form = MascotasForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:mascotas")
        else:
            errors = form.errors
            context = {
                'form': form,
                'errors': errors
            }
            return render(request, 'movies/new_mascotas.html', context)
    else:
        form = MascotasForm()
        context = {
            'form': form
        }
        return render(request, 'movies/new_mascotas.html', context)


def list_mascotas(request):
    """View que enlista MovieList que hay en la base de datos."""
    lists = Mascotas.objects.all().order_by('nombre')
    context =  {
        'lists': lists
    }

    return render(request, 'movies/list_mascotas.html', context)

def detail_mascotas(request, id):
    """View que muestra el detalle de una lista."""
    object = get_object_or_404(Mascotas, pk=id)
    context = {
        'list': object
    }

    return render(request, 'movies/detail_mascotas.html', context)

def update_mascotas(request, id):
    """View para editar una lista."""
    object = get_object_or_404(Mascotas, pk=id)
    if request.method == "POST":
        form = MascotasForm(request.POST, instance=object)
        if form.is_valid():
            form.save()
            return redirect("movies:mascotas")
        else:
            errors = form.errors
            context = {
                'form': form,
                'errors': errors
            }
            return render(request, 'movies/new_mascotas.html', context)
    else:
        form = MascotasForm(instance=object)
        context = {
            'form': form,
            'list': object
        }
        return render(request, 'movies/new_mascotas.html', context)


def delete_mascotas(request, id):
    """
    View para borrar una lista. Si es un método GET, le pedimos confirmación
    al usuario. Si es un método POST, significa que el usuario ha confirmado
    y podemos borrar la lista.
    """
    object = get_object_or_404(Mascotas, pk=id)

    if request.method == "POST":
        object.delete()
        return redirect("movies:mascotas")
    else:
        return render(request, "movies/delete_mascotas.html", {'list': object})

		
""" Detalle desde los estados"""
def create_estados(request):
    """View para crear una nueva lista películas por ver."""
    if request.method == "POST":
        form = Estados(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:estados")
        else:
            errors = form.errors
            context = {
                'form': form,
                'errors': errors
            }
            return render(request, 'movies/new_estados.html', context)
    else:
        form = EstadosForm()
        context = {
            'form': form
        }
        return render(request, 'movies/new_estados.html', context)


def list_estados(request):
    """View que enlista MovieList que hay en la base de datos."""
    lists = Estados.objects.all().order_by('name')
    context =  {
        'lists': lists
    }

    return render(request, 'movies/list_estados.html', context)

def detail_estados(request, id):
    """View que muestra el detalle de una lista."""
    object = get_object_or_404(Mascotas, pk=id)
    context = {
        'list': object
    }

    return render(request, 'movies/detail_estados.html', context)

def update_estados(request, id):
    """View para editar una lista."""
    object = get_object_or_404(Estados, pk=id)
    if request.method == "POST":
        form = EstadosForm(request.POST, instance=object)
        if form.is_valid():
            form.save()
            return redirect("movies:estados")
        else:
            errors = form.errors
            context = {
                'form': form,
                'errors': errors
            }
            return render(request, 'movies/new_estados.html', context)
    else:
        form = EstadosForm(instance=object)
        context = {
            'form': form,
            'list': object
        }
        return render(request, 'movies/new_estados.html', context)


def delete_estados(request, id):
    """
    View para borrar una lista. Si es un método GET, le pedimos confirmación
    al usuario. Si es un método POST, significa que el usuario ha confirmado
    y podemos borrar la lista.
    """
    object = get_object_or_404(Mascotas, pk=id)

    if request.method == "POST":
        object.delete()
        return redirect("movies:estados")
    else:
        return render(request, "movies/delete_estados.html", {'list': object})


class InteresadosList(generics.ListCreateAPIView):
	queryset = Interesados.objects.all()
	serializer_class = interesasosSerializer	
	
	def get_object(self):
		queryset = self.get_queryset()
		obj = get_object_or_404(
			queryset,
			pk=self.kwargs['pk'],
			)
		return obj
			
class MascotasList(generics.ListCreateAPIView):
	queryset = Mascotas.objects.all()
	serializer_class = MascotaSerializer
	
	def get_object(self):
		queryset = self.get_queryset()
		obj = get_object_or_404(
			queryset,
			pk=self.kwargs['pk'],
			)
		return obj			

def index1(request):
    template='movies/index1.html'
    results=interesados.objects.all()
    context={
        'results':results,
    }
    return render(request,template,context)

movies/templates/movies/base.html
<!DOCTYPE html>
<html>
{% load pwa %}
{% load static %}
<head>
 {% progressive_web_app_meta %}
    <title>Interesados 33</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <style type="text/css">
        .dropdown-span{
            text-align: center;
            color: white;
            background-color: #5bc0de;
        }
        span{
            color: white;
        }
        .footer{
            text-align: center;
            position: absolute;
            padding:10px;
            color: white;
            width: 100%;
            bottom:0;
        }
        .alink{
            text-decoration: none;
            color: white;
        }
        .alink:hover{
            text-decoration: none;
            color: white;
        }
        #content{
            padding-bottom: 5%;
        }
        html,body{
            margin: 0;
            padding: 0;
            height: 100%;
        }
        .wrapper{
            position: relative;
            min-height: 100%;
        }
    </style>
</head>
<body>
    <div class="wrapper">   
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#"><h2>Interesados</h2></a> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">About us</a>
                        </li>
                </ul>
            </div>
        </nav>
        <div id="content" class="container">
            <br><br><br>
            {% block content %}

            {% endblock %}
        </div>
        <div class="footer bg-dark">
            <p>&copy Interesados</p>
            <a class="alink" href="#">Privacy policy</a>&nbsp
            <a class="alink" href="#">Contact us</a>
        </div>
    </div>
</body>
</html>

movies/templates/movies/delete_interesados.html
<form action="." method="post">
  {% csrf_token %}
  <h1>Si decides borrar la lista "{{ list.name }}", no podrás recuperarla.</h1>
  <input type="submit" value="Borrar lista.">
  <a href="{% url 'movies:detail_interesados' list.pk %}">Cancelar</a>
</form>

movies/templates/movies/delete_mascotas.html
<form action="." method="post">
  {% csrf_token %}
  <h1>Si decides borrar la lista "{{ list.name }}", no podrás recuperarla.</h1>
  <input type="submit" value="Borrar lista.">
  <a href="{% url 'movies:detail_interesados' list.pk %}">Cancelar</a>
</form>

movies/templates/movies/detail_estados.html
<h2>{{ list.estados.all.0}}</h2>


<p>Mascotas:</p>
<ul>
  {% for mascotas in list.estados.all %}
    <li>{{ list.nombre }}</li>
	<li>{{ list.image }}</li>
  {% endfor %}
</ul>

<a href="{% url 'movies:edit_estados' list.pk %}">Editar</a>
<a href="{% url 'movies:delete_estados' list.pk %}">Borrar</a>
<a href="{% url 'movies:estados' %}">Volver</a>

movies/templates/movies/detail_interesados.html
<h2>{{ list.nombrecompleto }}</h2>
<h4>Interesado: {{ list.owner.get_full_name }}</h4>

<p>Detalle del insteresado:</p>
<ul>
 <p><b>Nombre del interesado :{{ list.nombrecompleto }}</b></p>
 <p>Correo :{{ list.correo }}</p>
 <p>Teléfono :{{ list.telefono}} </p>
 <p>Región : {{ list.region.all.0 }}</p>
 <p>Ciudad :{{ list.ciudad.all.0 }}</p>
 <p>Vivienda :{{ list.vivienda.all.0}}</p>
 <p>Fecha Nacimiento :{{ list.fecha_nacimiento}}</p>
 
</ul>

<a href="{% url 'movies:edit_interesados' list.pk %}">Editar</a>
<a href="{% url 'movies:delete_interesados' list.pk %}">Borrar</a>
<a href="{% url 'movies:interesados' %}">Volver</a>

movies/templates/movies/detail_mascotas.html
<h2>{{ list.nombre }}</h2>
<h4>Interesado: {{ list.owner.get_full_name }}</h4>

<p>Detalle del insteresado:</p>
<ul>
 <p><b>Nombre Mascota :{{ list.nombre }}</b></p>
 <p>Raza predominante :{{ list.razap.all.0 }}</p>
 <p>descripcion :{{ list.descripcion}} </p>
 <p>Estados : {{ list.estados.all.0 }}</p>
 <p>Image :{{ list.image }}</p>
 
</ul>

<a href="{% url 'movies:edit_mascotas' list.pk %}">Editar</a>
<a href="{% url 'movies:delete_mascotas' list.pk %}">Borrar</a>
<a href="{% url 'movies:mascotas' %}">Volver</a>

movies/templates/movies/detail_watchlist.html
<h2>{{ list.name }}</h2>
<h4>Autor: {{ list.owner.get_full_name }}</h4>

<p>Películas:</p>
<ul>
  {% for movie in list.movies.all %}
    <li>{{ movie.name }}</li>
	<li>{{ 
  {% endfor %}
</ul>

<a href="{% url 'movies:edit_watchlist' list.pk %}">Editar</a>
<a href="{% url 'movies:delete_watchlist' list.pk %}">Borrar</a>
<a href="{% url 'movies:watchlists' %}">Volver</a>

movies/templates/movies/index.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Sistema de Mascotas</title>
</head>
<body>
<link rel="stylesheet" type="{% static "css/stilo.css"%}">
{% block title %}Login{% endblock %}

{% block content %}
{{ csrf_token }}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}
<table>
<p>  </p>
{% load socialaccount %}
<p></p><a class="btn btn-primary btn-block" href="{% provider_login_url "facebook" method="oauth2" %}">
   <span class="fab fa-facebook"></span>
      LOGIN CON FACEBOOK
 </a>
</p>
</table>
</body>
</html>

movies/templates/movies/index1.html
{% extends 'movies/base.html' %}
{% block content %}
{% load static %}
<br><br><br>
<div class="feeds">
	{% for result in results %}
		<h3>{{result.rut}}</h3>
		<br>
		Name:{{result.nombrecompleto}}
		<br>
		<p id="{{result.id}}">
			{{result.telefono}}
		</p>
		<hr>
	{% endfor %}
</div>
{% endblock %}

movies/templates/movies/list_estados.html
<h2>Lista de los Estados disponibles</h2>

<ul>
  {% for list in lists %}
    <li><a href="{% url 'movies:detail_estados' list.pk %}">{{ list }}</a></li>
  {% endfor %}
</ul>

<a href="{% url 'movies:new_estados' %}">Crear nuevo Estado</a>
<p><a href="{% url 'movies:mascotas' %}">Listar Mascotas</a></p>
<p><a href="{% url 'movies:interesados' %}">Listar Interesados</a></p>

movies/templates/movies/list_interesados.html
<h2>Lista de Interesados.</h2>

<ul>
  {% for list in lists %}
    <li><a href="{% url 'movies:detail_interesados' list.pk %}">{{ list }}</a></li>
  {% endfor %}
</ul>

<a href="{% url 'movies:new_interesados' %}">Crear un nuevo interesado</a>

movies/templates/movies/list_mascotas.html
<h2>Listado de Mascotas</h2>
<div>
<ul>
  {% for list in lists %}
    <li><a href="{% url 'movies:detail_mascotas' list.pk %}">{{ list }}</a></li>
  {% endfor %}
</ul>

<a href="{% url 'movies:new_mascotas' %}">Crear una nueva mascota</a>
</div>

movies/templates/movies/list_watchlists.html
<h2>Lista de películas por ver.</h2>

<ul>
  {% for list in lists %}
    <li><a href="{% url 'movies:detail_watchlist' list.pk %}">{{ list }}</a></li>
  {% endfor %}
</ul>

<a href="{% url 'movies:new_watchlist' %}">Crear nueva lista</a>

movies/templates/movies/new_mascotas.html
<h2>Mascotas</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Enviar">
</form>

{% if list %}
  <a href="{% url 'movies:detail_mascotas' list.pk %}">Cancelar</a>
{% else %}
  <a href="{% url 'movies:mascotas' %}">Cancelar</a>
{% endif %}